spring:
  application:
    name: Customer-Application
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test?autoreconnect=true
    username: root
    password: root



//  autoconfigure:
//    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration